"""add_user_personalization_fields_v2

Revision ID: 97600f4405a9
Revises: 8f36e3b2f489
Create Date: 2026-01-10 23:23:09.186915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97600f4405a9'
down_revision: Union[str, Sequence[str], None] = '8f36e3b2f489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabilities', sa.String(), nullable=True))
    op.add_column('users', sa.Column('interests', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_analogies', sa.String(), nullable=True))
    op.add_column('users', sa.Column('learning_style', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'learning_style')
    op.drop_column('users', 'preferred_analogies')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'disabilities')
    # ### end Alembic commands ###
